import {Product} from '../assets/product';
export const product:Product[]=[
    {
        categoryId:1,
        productId:1,
        name: 'iPhone 12 Pro Max',
        description:'iPhone 12 Pro Max, 128GB, Graphite',
        price:'$1099.99',
        img:'https://m.media-amazon.com/images/I/71XXJC7V8tL._FMwebp__.jpg',
        link:'https://www.amazon.com/dp/B08L5R1CCC/ref_=vn_s_iwp_0?pd_rd_w=74xZ9&pf_rd_p=84cbcc8f-0fe2-44fc-ae2a-87f8b101dbca&pf_rd_r=4HWEFSE48NJ3M4VSXETX&pd_rd_r=86383384-9541-4b19-89a0-d9be5afa67f2&pd_rd_wg=VqkTF&qid=1614036067#',
        rating:10,
        like:12,
        isLiked:false,
        isRemoved:false
    },
    {
        categoryId:1,
        productId:2,
        name:'iPhone 12 Pro',
        description:"iPhone 12 Pro, 128GB, Pacific Blue",
        price:'$830.99',
        img:'https://m.media-amazon.com/images/I/71DVgBTdyLL._FMwebp__.jpg',
        link:'https://www.amazon.com/dp/B08L5NRZNW/ref=fs_a_iwp2_1#',
        rating:9.5,
        like:13,
        isLiked:false,
        isRemoved:false
    },
    {
        categoryId:1,
        productId:3,
        name:'iPhone 12 Mini',
        description:"iPhone 12 Mini, 64GB, RED",
        price:'$699.99',
        img:'https://m.media-amazon.com/images/I/71Sa8+9H3xL._FMwebp__.jpg',
        link:'https://www.amazon.com/dp/B08L5RJ392/ref_=vn_s_iwp_3?pd_rd_w=tjKfy&pf_rd_p=84cbcc8f-0fe2-44fc-ae2a-87f8b101dbca&pf_rd_r=ET81HRE554ESXGX1RABA&pd_rd_r=74e26584-58ca-4849-a861-7ed6c3257c43&pd_rd_wg=ue4yx&qid=1614102361#',
        rating:9.9,
        like:14,
        isLiked:false,
        isRemoved:false
    },
    {
        categoryId:1,
        productId:4,
        name:"iPhone SE",
        description:"iPhone SE, 64GB, Black",
        price:'$279.99',
        img:'https://store.storeimages.cdn-apple.com/4668/as-images.apple.com/is/iphone-se-white-select-2020_GEO_EMEA?wid=834&hei=1000&fmt=jpeg&qlt=95&op_usm=0.5,0.5&.v=1586574260599',
        link:'https://www.amazon.com/dp/B0875RT5WS/ref=fs_a_iwp2_4',
        rating:9,
        like:15,
        isLiked:false,
        isRemoved:false
    },
    {
        categoryId:1,
        productId:5,
        name:'iPhone 11 Pro Max',
        description:"iPhone 11 Pro Max, 64GB, Midnight Green",
        price:'$999.99',
        img:'https://m.media-amazon.com/images/I/81j2j9x-KWL._FMwebp__.jpg',
        link:'https://www.amazon.com/dp/B0844JKGSK/ref_=vn_s_iwp1_0?pd_rd_w=eAkes&pf_rd_p=61c17cb9-4bb8-40ea-b5b5-77e848e967a8&pf_rd_r=GBQ64CRA8GQKM223B09Z&pd_rd_r=15a0ea01-030c-4f5b-b005-1a00c09baf2b&pd_rd_wg=R74I7&qid=1614105361',
        rating:9.9,
        like:16,
        isLiked:false,
        isRemoved:false
    },
    {
        categoryId:2,
        productId:1,
        name:'MacBook Pro',
        description:"Apple M1 Chip (13-inch, 8GB RAM, 256GB SSD Storage) - Silver (Latest Model)",
        price:'$1209.92',
        img:'https://images-na.ssl-images-amazon.com/images/I/71gD8WdSlaL._AC_SL1500_.jpg',
        link:'https://www.amazon.com/Apple-MacBook-13-inch-256GB-Storage/dp/B08N5LLDSG/ref=sr_1_1?dchild=1&keywords=macbook&qid=1614716348&sr=8-1',
        rating:9.9,
        like:17,
        isLiked:false,
        isRemoved:false
    },
    {
        categoryId:2,
        productId:2,
        name:"MacBook Air",
        description:"Apple M1 Chip (13-inch, 8GB RAM, 256GB SSD Storage) - Silver",
        price:'$995.95',
        img:'https://images-na.ssl-images-amazon.com/images/I/71TPda7cwUL._AC_SL1500_.jpg',
        link:'https://www.amazon.com/dp/B08N5KWB9H/ref=fs_a_mbt2_us1',
        rating:9.5,
        like:18,
        isLiked:false,
        isRemoved:false
    },
    {
        categoryId:2,
        productId:3,
        name:"MacBook Pro",
        description:"(16-inch, 16GB RAM, 512GB Storage, 2.6GHz Intel Core i7) - Space Gray",
        price:'$2184.92',
        img:'https://images-na.ssl-images-amazon.com/images/I/71pC69I3lzL._AC_SL1500_.jpg',
        link:'https://www.amazon.com/dp/B081FZV45H/ref=fs_a_mbt2_us3',
        rating:10,
        like:19,
        isLiked:false,
        isRemoved:false
    },
    {
        categoryId:2,
        productId:4,
        name:"MacBook Air",
        description:"(13-inch Retina Display, 8GB RAM, 256GB SSD Storage) - Gold (Previous Model)",
        price:'$899.92',
        img:'https://images-na.ssl-images-amazon.com/images/I/71thf1SYnGL._AC_SL1500_.jpg',
        link:'https://www.amazon.com/Apple-MacBook-13-inch-256GB-Storage/dp/B08636NKF8/ref=sr_1_5?dchild=1&keywords=macbook&qid=1614716630&sr=8-5',
        rating:8.5,
        like:20,
        isLiked:false,
        isRemoved:false
    },
    {
        categoryId:2,
        productId:5,
        name:"MacBook Pro",
        description:"with Touch Bar, 10th-Generation Quad-Core Intel Core i7 2.3GHz, 16GB RAM, 512GB SSD, Space Gray (Mid 2020)",
        price:'1999.99',
        img:'https://images-na.ssl-images-amazon.com/images/I/61gcCcu6VQL._AC_SL1200_.jpg',
        link:'https://www.amazon.com/Apple-MacBook-Pro-10th-Generation-Quad-Core/dp/B08DTPQ9XB/ref=sr_1_6?dchild=1&keywords=macbook&qid=1614716630&sr=8-6',
        rating:5,
        like:21,
        isLiked:false,
        isRemoved:false
    },
    {
        categoryId:3,
        productId:1,
        name:"Apple Watch Series 3",
        description:"(GPS, 38mm) - Space Gray Aluminum Case with Black Sport Band",
        price:'$542.41',
        img:'https://images-na.ssl-images-amazon.com/images/I/71fwbMm1NBL._AC_SL1500_.jpg',
        link:'https://www.amazon.com/Apple-Watch-GPS-38mm-Space-Aluminium/dp/B07K39FRSL/ref=sr_1_2?crid=2RCVGQYHU1UOI&dchild=1&keywords=apple%2Bwatch&qid=1614716882&sprefix=apple%2B%2Caps%2C351&sr=8-2&th=1',
        rating:8.5,
        like:22,
        isLiked:false,
        isRemoved:false
    },
    {
        categoryId:3,
        productId:2,
        name:"Apple Watch Series 6",
        description:"(GPS + Cellular, 40mm) - Graphite Stainless Steel Case with Black Sport Band",
        price:'$548.99',
        img:'https://images-na.ssl-images-amazon.com/images/I/71OCKffe7SL._AC_SL1500_.jpg',
        link:'https://www.amazon.com/dp/B08J5VR31T/ref=fs_a_wt2_us0',
        rating:10,
        like:23,
        isLiked:false,
        isRemoved:false
    },
    {
        categoryId:3,
        productId:3,
        name:"Apple Watch SE",
        description:"(GPS, 40mm) - Space Gray Aluminum Case with Black Sport Band",
        price:'$580.90',
        img:'https://images-na.ssl-images-amazon.com/images/I/71NVDjayU9L._AC_SL1500_.jpg',
        link:'https://www.amazon.com/dp/B08J5W9QWZ/ref=fs_a_wt2_us3',
        rating:9.4,
        like:24,
        isLiked:false,
        isRemoved:false
    },
    {
        categoryId:3,
        productId:4,
        name:"Apple Watch Series 6",
        description:"(GPS, 40mm) - Space Gray Aluminum Case with Black Sport Band",
        price:'$797.82',
        img:'https://images-na.ssl-images-amazon.com/images/I/71yOGVLGWpL._AC_SL1500_.jpg',
        link:'https://www.amazon.com/dp/B08J5QC43Q/ref=fs_a_wt2_us1',
        rating:9.5,
        like:25,
        isLiked:false,
        isRemoved:false
    },
    {
        categoryId:3,
        productId:5,
        name:"Apple Watch SE",
        description:"(GPS + Cellular, 40mm) - Space Gray Aluminum Case with Black Sport Band",
        price:'$520.00',
        img:'https://images-na.ssl-images-amazon.com/images/I/71LMdayAMCL._AC_SL1500_.jpg',
        link:'https://www.amazon.com/dp/B08J5V7H7J/ref=fs_a_wt2_us2',
        rating:9.8,
        like:26,
        isLiked:false,
        isRemoved:false
    },
    {
        categoryId:4,
        productId:1,
        name:"Apple AirPods Max",
        description:"Space Gray-NFC, Bluetooth, Transparancy, Audio Sharing, Wireless",
        price:'$714.99',
        img:'https://images-na.ssl-images-amazon.com/images/I/81jqUPkIVRL._AC_SL1500_.jpg',
        link:'https://www.amazon.com/dp/B08PZHYWJS/ref=fs_a_mdt2_us0',
        rating:9.5,
        like:27,
        isLiked:false,
        isRemoved:false
    },
    {
        categoryId:4,
        productId:2,
        name:"AirPods Pro",
        description:"White-Wireless-In Ear-Active noise cancellation for immersive sound",
        price:'$613.49',
        img:'https://images-na.ssl-images-amazon.com/images/I/71zny7BTRlL._AC_SL1500_.jpg',
        link:'https://www.amazon.com/dp/B07ZPC9QD4/ref=fs_a_mdt2_us1',
        rating:9,
        like:28,
        isLiked:false,
        isRemoved:false
    },
    {
        categoryId:4,
        productId:3,
        name:"AirPods 2",
        description:"AirPods-Bluetooth, NFC-Universal fit that’s comfortable all day",
        price:'$515.99', 
        img:'https://images-na.ssl-images-amazon.com/images/I/710rzW2RGcL._AC_SL1500_.jpg',
        link:'https://www.amazon.com/Apple-AirPods-Wireless-Charging-Latest/dp/B07PYLT6DN/ref=sr_1_1?dchild=1&keywords=airpods+2&qid=1614717450&sr=8-1',
        rating:9.9,
        like:29,
        isLiked:false,
        isRemoved:false
    },
]